apihealth:
  - name: Ripple API
    url: ${API_HEALTH_URL}
    max_age: 12h
    timeout: 15s
    interval: 2m
    alert:
      strategy: regular
      factor: 720
      max: 10
    channels:
      - email-alerts

notify:
  email:
    - name: email-alerts
      server: smtp.gmail.com:587
      username: zhouchintse@gmail.com
      password: "${GMAIL_APP_PASSWORD}"
      to: "jerry@orcas-coastal.com;dougal@orcas-coastal.com"
      channels:
        - email-alerts

settings:
  probe:
    timeout: 30s
    interval: 2m
  sla:
    schedule: weekly
    time: "00:00"
    channels:
      - email-alerts
